---
- name: Start seeding service
  become: true
  ansible.builtin.systemd:
    state: started
    name: snapd.seeded

# This is a Hack needs replaced! It should dynamically monitor the "systemctl status snapd.seeded.service" until ready. 
- name: Wait until seeding ready
  ansible.builtin.wait_for:
    timeout: "{{ seconds_to_wait_for_seeding }}"
  delegate_to: localhost

- name: Reconnect
  ansible.builtin.meta: reset_connection

- name: Snap install core
  community.general.snap:
    name:
      - core
  become: true