- debug:
    msg: "{{ ansible_distribution_major_version }}"

- name: Enable snapd
  ansible.builtin.dnf:
    name:
      - snapd
    state: latest
  become: true
  notify:
    - Start seeding service
    - Wait until seeding ready
# This is a Hack needs replaced! It should dynamically monitor the "systemctl status snapd.seeded.service" until ready.

### Try
# - name: is snapd.seeded.service done
#   command: wait until systemctl status snapd.seeded.service
### Try

- name: Enable classic snap support
  ansible.builtin.file:
    src: /var/lib/snapd/snap
    dest: /snap
    state: link
  become: true

# https://snapcraft.io/install/snapcraft/fedora
